version: '3.7'

services:
  backend:
    container_name: flask-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app

  client:
    container_name: starter-client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './:/starter-client'
      - '/usr/src/starter-client/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "backend"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true