version: '3.7'

services:
  backend:
    container_name: starter-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  client:
    container_name: starter-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/client
    ports:
      - '3000:3000'
    depends_on:
      - "backend"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

