dashboard:
  layout:               terminal-ide-web
  hideMessages:         false
  iframeUrl:            /webservice
  showUrlBar:           false
  terminalMenuItem:     terminal
  reloadIframeOnDeploy: false
  enabledLayouts:       
                        - terminal-ide-web
                        - terminal-ide-vertical
                        - terminal-web
                        - ide-web-vertical
                        - terminal-ide-horizontal
                        - terminal-only
                        - ide-only
                        - web-only
ide:
  autoSaveInterval:     444
  showDeployButton:     true
  deployButtonText:
                        TODEPLOY:  Deploy
                        DEPLOYED:  Deployed
                        DEPLOYING: Reloading app...
                        FAILED:    Deployment failed
site:
  askReloadSite:        false
  documentTitle:        Avatao Tutorials
