import os

__DEFAULT_WORKDIR = '/tmp/workdir '
__DEFAULT_SOURCEDIR = f'{__DEFAULT_WORKDIR}/avatao_startr/tfw'

STARTER_WORKDIR = os.environ.get("TFW_STARTER_WORKING_DIRECTORY", __DEFAULT_WORKDIR)
STARTER_SOURCEDIR = os.environ.get("TFW_STARTER_SOURCE_DIRECTORY", __DEFAULT_SOURCEDIR)