FROM avatao/tutorial:ragdoll-20201201

ENV TFW_WEBSERVICE_DIR=/home/user/webservice

COPY solvable/supervisor /etc/supervisor
COPY solvable/webservice $TFW_WEBSERVICE_DIR

# Custom commands
{% if data -%}
    {% for command in data -%}
{{ command }}
    {%- endfor %}
{%- endif %}

VOLUME ["/home/user"]