FROM avatao/tutorial:ragdoll-20201201

ENV TFW_WEBSERVICE_DIR=/home/user/webservice

COPY solvable/supervisor /etc/supervisor
COPY solvable/webservice $TFW_WEBSERVICE_DIR

# Install Node.js
RUN apt-get update -yq \
    && apt-get -yq install curl gnupg ca-certificates \
    && curl -L https://deb.nodesource.com/setup_12.x | bash \
    && apt-get update -yq \
    && apt-get install -yq \
        dh-autoreconf=19 \
        ruby=1:2.5.* \
        ruby-dev=1:2.5.* \
        nodejs

# Custom commands
{% if data -%}
    {% for command in data -%}
{{ command }}
    {%- endfor %}
{%- endif %}

VOLUME ["/home/user"]