---
# Upgraded from v3.0
crp_config:
  controller:
    ports:
    - 5555/controller
  solvable:
    capabilities:
    - SETUID
    - SETGID
    - CHOWN
    - AUDIT_WRITE
    - DAC_OVERRIDE
    - KILL
    mem_limit_mb: 300
    ports:
    - 8888/http
crp_type: docker
enable_flag_input: false
version: v3.1