FROM avatao/baseimage-tutorial-framework

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
  apt-get install -y nodejs

# Install node
RUN apt-get update \
  && apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst --no-install-recommends \
  && apt-get install -qy gconf-service \
	libasound2 \
	libatk1.0-0 \
	libc6 \
	libcairo2 \
	libcups2 \
	libdbus-1-3 \
	libexpat1 \
	libfontconfig1  \
	libgcc1  \
	libgconf-2-4  \
	libgdk-pixbuf2.0-0  \
	libglib2.0-0  \
	libgtk-3-0  \
	libnspr4  \
	libpango-1.0-0  \
	libpangocairo-1.0-0  \
	libstdc++6  \
	libx11-6  \
	libx11-xcb1  \
	libxcb1  \
	libxcomposite1  \
	libxcursor1 \
	libxdamage1 \
	libxext6 \
	libxfixes3  \
	libxi6  \
	libxrandr2  \
	libxrender1  \
	libxss1 \
	libxtst6  \
	ca-certificates  \
	fonts-liberation \
	libappindicator1 \
	libnss3  \
	lsb-release \
	xdg-utils \
  libgbm-dev \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g  n && \
    n 12.18.3

RUN npm install -g puppeteer@5.3.0 --unsafe-perm && \
    npm link puppeteer@5.3.0 --unsafe-perm

RUN  groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
  && mkdir -p /home/pptruser/Downloads \
  && chown -R pptruser:pptruser /home/pptruser

# Define variables to use later
ENV TFW_EHMAIN_DIR="${TFW_DIR}/builtin_event_handlers" \
    TFW_WEBSERVICE_DIR="/srv/webservice"               \
    TFW_IDE_WD="/home/${AVATAO_USER}/workdir"          \
    TFW_TERMINADO_WD="/home/${AVATAO_USER}/workdir"

# Copy TFW related stuff to a dedicated directory
COPY solvable/src ${TFW_EHMAIN_DIR}/

# Copy webservice to a dedicated directory
COPY solvable/src/webservice/ ${TFW_WEBSERVICE_DIR}/

# Framework specific instructions
{{ framework_commands }}

# Create IDE directory, symlink server source and give proper permissions to AVATAO_USER
RUN mkdir -p ${TFW_IDE_WD}                                               &&\
    chown -R ${AVATAO_USER}: "${TFW_IDE_WD}" "${TFW_WEBSERVICE_DIR}"     &&\
    chmod -R 755 "${TFW_IDE_WD}" "${TFW_WEBSERVICE_DIR}"

# Hide TFW related code from user
RUN chown -R root:root ${TFW_SERVER_DIR} ${TFW_DIR} &&\
    chmod -R 700 ${TFW_SERVER_DIR} ${TFW_DIR}

# Make AVATAO_USER's home writeable and set it as WORKDIR
# Make webservice directory writable
VOLUME ["/home/${AVATAO_USER}", "${TFW_WEBSERVICE_DIR}"]
WORKDIR /home/${AVATAO_USER}
